# Generated by Django 4.2 on 2025-10-30 11:02

import apps.file_manager.models
import autoslug.fields
import django.contrib.postgres.search
from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.IntegerField(blank=True, null=True)),
                ('dynamic_similarity', models.BooleanField(default=False)),
                ('dynamic_rows', models.IntegerField(blank=True, null=True)),
                ('extract_keywords', models.BooleanField(default=True)),
                ('filter_method', models.CharField(choices=[('vector', 'Vector'), ('graic', 'grAIc')], default='vector', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.file_manager.models.upload_file_with_dir)),
                ('action_status', models.CharField(choices=[('IS_ACTIVE', 'Is Active'), ('DELETED', 'Deleted')], default='IS_ACTIVE', max_length=50)),
                ('file_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=50, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Invoice', 'Invoice'), ('Statement', 'Statement')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('vector_model', models.CharField(default=apps.file_manager.models.get_current_vector_model, max_length=255)),
                ('fts', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('chunk_text', models.TextField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('action_status', models.CharField(choices=[('IS_ACTIVE', 'Is Active'), ('DELETED', 'Deleted')], default='IS_ACTIVE', max_length=50)),
                ('folder_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
