# Generated by Django 4.2 on 2025-10-30 11:02

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('file_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_manager.filemanager'),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sidebar'),
        ),
        migrations.AddField(
            model_name='filemanager',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_file_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_manager.filemanager'),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='filechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts'], name='file_manage_fts_6de1ba_gin'),
        ),
    ]
