# Generated by Django 4.2 on 2026-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
    ]
