# Generated by Django 4.2 on 2025-10-30 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manifest', models.TextField()),
                ('system_prompt', models.TextField()),
                ('llm', models.CharField(blank=True, max_length=255, null=True)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPrePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Analyst', max_length=255)),
                ('name', models.CharField(default='grAIc', max_length=255)),
                ('date', models.DateField(default=datetime.date.today, verbose_name="Today's date")),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='Current time')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('file', 'File'), ('dt', 'DT')], default='file', max_length=10)),
                ('workflow', models.CharField(choices=[('summary', 'Summary')], default='summary', max_length=255)),
                ('prompt', models.TextField()),
                ('email_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('type', 'workflow')},
            },
        ),
        migrations.CreateModel(
            name='Graic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('thinking', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('time_take', models.FloatField(blank=True, null=True)),
                ('is_dt', models.BooleanField(default=False)),
                ('summary_response', models.TextField(blank=True, null=True)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_files/')),
                ('type', models.CharField(choices=[('file', 'File'), ('dt', 'DT')], default='file', max_length=10)),
                ('feedback', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='graic.chat')),
            ],
            options={
                'verbose_name': 'grAIc',
                'verbose_name_plural': 'grAIc',
            },
        ),
    ]
