# Generated by Django 4.2 on 2025-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='search_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
