# Generated by Django 4.2 on 2025-11-24 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tables', '0003_tab_search_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCharts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_view', models.TextField()),
                ('name', models.TextField(default='Charts', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('base_view', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TabCharts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('x_field', models.CharField(max_length=100)),
                ('y_field', models.CharField(blank=True, max_length=100, null=True)),
                ('chart_type', models.CharField(choices=[('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart')], default='BAR', max_length=20)),
                ('info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('base_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.basecharts')),
                ('parent_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tab')),
            ],
        ),
    ]
