# Generated by Django 4.2 on 2026-01-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_savedfilter_chart_id_alter_savedfilter_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0004_basecharts_tabcharts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecharts',
            options={'verbose_name': 'Base Chart', 'verbose_name_plural': 'Base Charts'},
        ),
        migrations.AlterModelOptions(
            name='tabcharts',
            options={'verbose_name': 'Tab Chart', 'verbose_name_plural': 'Tab Charts'},
        ),
        migrations.AlterUniqueTogether(
            name='basecharts',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basecharts',
            name='saved_filters',
            field=models.ManyToManyField(blank=True, to='common.savedfilter'),
        ),
        migrations.AddField(
            model_name='tabcharts',
            name='color',
            field=models.CharField(default='#008FFB', max_length=100, verbose_name='Bar or Line color'),
        ),
        migrations.AlterField(
            model_name='daterangefilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='floatrangefilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hideshowfilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intrangefilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pageitems',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedrows',
            name='model_choice',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='serverfilter',
            name='parent',
            field=models.CharField(choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='Financial_system_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='Financial_system_Last_Used', null=True, verbose_name='Financial_system_Last_Used'),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='HR_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='HR_Last_Used', null=True, verbose_name='HR_Last_Used'),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='Payroll_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='Payroll_Last_Used', null=True, verbose_name='Payroll_Last_Used'),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='SAP_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='SAP_Last_Used', null=True, verbose_name='SAP_Last_Used'),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='SPLUNK_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='SPLUNK_Last_Used', null=True, verbose_name='SPLUNK_Last_Used'),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='Servicenow_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='Servicenow_Last_Used', null=True, verbose_name='Servicenow_Last_Used'),
        ),
        migrations.AlterField(
            model_name='unifiedaccessmanagement',
            name='VPN_Last_Used',
            field=models.BigIntegerField(blank=True, db_column='VPN_Last_Used', null=True, verbose_name='VPN_Last_Used'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='parent',
            field=models.CharField(blank=True, choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('CHART', 'Chart'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ScheduledChartExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.TextField(blank=True, null=True)),
                ('export_type', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], max_length=10)),
                ('export_option', models.CharField(default='grc', max_length=10)),
                ('frequency', models.CharField(choices=[('once', 'One time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('hour_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custom_prompt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tabcharts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
