# Generated by Django 4.2 on 2026-02-02 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0005_alter_basecharts_options_alter_tabcharts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImpactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SECURITY_BREACH', 'Security breach risk'), ('FINANCIAL_LOSS', 'Financial loss'), ('REGULATORY_NON_COMPLIANCE', 'Regulatory non-compliance'), ('OPERATIONAL_DISRUPTION', 'Operational disruption'), ('REPUTATIONAL_DAMAGE', 'Reputational damage')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('inherent_impact', models.CharField(choices=[('INSIGNIFICANT', 'Insignificant'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('SEVERE', 'Severe')], max_length=20)),
                ('likelihood', models.CharField(choices=[('FREQUENT', 'A-Frequent'), ('PROBABLE', 'B-Probable'), ('OCCASIONAL', 'C-Occasional'), ('REMOTE', 'D-Remote'), ('IMPROGRABLE', 'E-Improbable'), ('ELIMINATED', 'F-Eliminated')], max_length=20)),
                ('residual_risk', models.CharField(choices=[('CATASTROPHIC', '1-Catastrophic'), ('CRITICAL', '2-Critical'), ('MARGINAL', '3-Marginal'), ('NEGLIGIBLE', '4-Negligible')], max_length=20)),
                ('confidence', models.CharField(choices=[('HIGH', 'High (100%)'), ('MEDIUM', 'Medium (70%)'), ('LOW', 'Low (30%)')], max_length=20)),
                ('primary_root_cause', models.CharField(choices=[('PROCESS_GAP', 'Process gap'), ('POLICY_NOT_ENFORCED', 'Policy not enforced'), ('SYSTEM_CONFIGURATION', 'System configuration'), ('HUMAN_ERROR', 'Human error'), ('TOOL_LIMITATION', 'Tool limitation'), ('THIRD_PARTY_DEPENDENCY', 'Third-party dependency')], max_length=50)),
                ('secondary_root_cause', models.CharField(blank=True, choices=[('PROCESS_GAP', 'Process gap'), ('POLICY_NOT_ENFORCED', 'Policy not enforced'), ('SYSTEM_CONFIGURATION', 'System configuration'), ('HUMAN_ERROR', 'Human error'), ('TOOL_LIMITATION', 'Tool limitation'), ('THIRD_PARTY_DEPENDENCY', 'Third-party dependency')], max_length=50, null=True)),
                ('audit_recommendation', django_quill.fields.QuillField(blank=True, null=True)),
                ('recommended_owner_role', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('SECURITY', 'Security'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('VENDOR', 'Vendor')], max_length=20)),
                ('target_remediation_date', models.DateField()),
                ('management_response', models.TextField(blank=True, null=True)),
                ('agreed_action_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='basecharts',
            name='chart_type',
            field=models.CharField(choices=[('BASE_CHART', 'Base Chart'), ('RISK_CHART', 'Risk Chart')], default='BASE_CHART', max_length=100),
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.riskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRiskExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.TextField(blank=True, null=True)),
                ('export_type', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], max_length=10)),
                ('export_option', models.CharField(default='grc', max_length=10)),
                ('frequency', models.CharField(choices=[('once', 'One time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('hour_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custom_prompt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.riskassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='base_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.basecharts'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='business_impacts',
            field=models.ManyToManyField(blank=True, to='tables.businessimpactitem'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='parent_tab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.tab'),
        ),
        migrations.CreateModel(
            name='ChartPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('base_chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.basecharts')),
            ],
        ),
    ]
