# Generated by Django 4.2 on 2026-02-03 12:09

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_businessimpactitem_riskassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('SECURITY', 'Security'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('VENDOR', 'Vendor')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='recommended_owner_role',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='recommended_owner_role',
            field=models.ManyToManyField(blank=True, to='tables.ownerrole'),
        ),
    ]
