# Generated by Django 4.2 on 2025-10-30 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PyFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('func', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PyFunctionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('base_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('delta_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('base_f_key_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('delta_f_key_fields', models.TextField(blank=True, help_text='Comma separated', null=True)),
                ('join_method', models.CharField(blank=True, max_length=255, null=True)),
                ('similarity_threshold', models.IntegerField(blank=True, null=True)),
                ('split_by_space', models.BooleanField(default=False)),
                ('split_character', models.CharField(blank=True, max_length=20, null=True)),
                ('match_word_position', models.IntegerField(blank=True, null=True)),
                ('pre_char', models.IntegerField(blank=True, null=True)),
                ('post_char', models.IntegerField(blank=True, null=True)),
                ('jaro_winkler', models.BooleanField(default=False)),
                ('levenshtein', models.BooleanField(default=False)),
                ('token_set_ratio', models.BooleanField(default=False)),
                ('phonetic', models.BooleanField(default=False)),
                ('fuzzy_wuzzy', models.BooleanField(default=False)),
                ('python_function', models.TextField(blank=True, null=True)),
                ('c_similarity_threshold', models.IntegerField(blank=True, null=True)),
                ('split_at', models.CharField(blank=True, max_length=20, null=True)),
                ('left_split_char', models.CharField(blank=True, max_length=20, null=True)),
                ('email_pre_char', models.IntegerField(blank=True, null=True)),
                ('email_post_char', models.IntegerField(blank=True, null=True)),
                ('base_model', models.ForeignKey(limit_choices_to={'app_label__in': ['tables', 'common']}, on_delete=django.db.models.deletion.CASCADE, related_name='base_model', to='contenttypes.contenttype')),
                ('delta_model', models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['tables', 'common']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delta_model', to='contenttypes.contenttype')),
                ('sidebar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sidebar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, choices=[('SAGE_USER_LIST', 'SAGEUserList'), ('CONTROL_AD_USER', 'ControlADUser'), ('CHANGE_REQUESTS', 'ChangeRequests'), ('HR_USER_LIST', 'HRUserList'), ('TICKET_LOGGING', 'TicketLogging'), ('UNIFIED_ACCESS_MANAGEMENT', 'UnifiedAccessManagement'), ('FAVORITE', 'Favorite'), ('UNIQUE', 'Unique'), ('FINDING', 'Finding'), ('TAB', 'Tab'), ('COPY_DT', 'Copy DT'), ('FINDING_VIEW', 'Finding View'), ('IMAGE_LOADER', 'Image Loader'), ('IMAGES', 'Images'), ('FINDING_ATTACHMENT', 'Finding Attachment')], max_length=255, null=True)),
                ('description', models.TextField()),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite_id', models.TextField(blank=True, null=True)),
                ('finding_id', models.TextField(blank=True, null=True)),
                ('img_loader_id', models.TextField(blank=True, null=True)),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('tab_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('column_order', models.JSONField()),
                ('favorite_id', models.TextField(blank=True, null=True)),
                ('finding_id', models.TextField(blank=True, null=True)),
                ('img_loader_id', models.TextField(blank=True, null=True)),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('tab_id', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
